services:
  traefik:
    command:
      - "--api.insecure=false"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "19876:19876"

  api:
    restart: unless-stopped
    deploy:
      replicas: 2

  frontend:
    restart: unless-stopped
