import type { Issue } from './issue'
export type { Issue } from './issue'

export interface BoardColumn {
  id: string
  name: string
  wipLimit: number | null
  issueIds: string[]
}

export interface Sprint {
  id: string
  name: string
  goal: string
  state: 'future' | 'active' | 'closed'
  velocity: number
  remainingDays: number | null
  issueIds: string[]
}

export const backlogIssues: Issue[] = [
  {
    id: 'issue-1',
    key: 'TT-1',
    summary: 'Implement auth',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'To Do',
    assigneeId: 'user-2',
    assigneeName: 'Ivan',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'High',
    labels: ['backend', 'auth'],
    dueDate: '2026-08-15',
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: 4 * 3600,
    remainingEstimateSeconds: 4 * 3600,
    timeSpentSeconds: 0,
  },
  {
    id: 'issue-2',
    key: 'TT-2',
    summary: 'Setup CI/CD',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'To Do',
    assigneeId: 'user-3',
    assigneeName: 'Anna',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'Medium',
    labels: ['devops'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: 2 * 3600,
    remainingEstimateSeconds: 2 * 3600,
    timeSpentSeconds: 0,
  },
  {
    id: 'issue-3',
    key: 'TT-3',
    summary: 'Design system tokens',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'To Do',
    assigneeId: 'user-4',
    assigneeName: 'Petr',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'Low',
    labels: ['ui'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: null,
    remainingEstimateSeconds: null,
    timeSpentSeconds: 0,
  },
  {
    id: 'issue-4',
    key: 'TT-4',
    summary: 'User profile page',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'To Do',
    assigneeId: 'user-3',
    assigneeName: 'Anna',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'Medium',
    labels: ['frontend'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: 6 * 3600,
    remainingEstimateSeconds: 6 * 3600,
    timeSpentSeconds: 0,
  },
  {
    id: 'issue-5',
    key: 'TT-5',
    summary: 'Email notifications',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'To Do',
    assigneeId: 'user-4',
    assigneeName: 'Petr',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'Low',
    labels: ['backend'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: null,
    remainingEstimateSeconds: null,
    timeSpentSeconds: 0,
  },
  {
    id: 'issue-6',
    key: 'TT-6',
    summary: 'Upgrade dependencies',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'To Do',
    assigneeId: 'user-2',
    assigneeName: 'Ivan',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'Low',
    labels: ['devops'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: null,
    remainingEstimateSeconds: null,
    timeSpentSeconds: 0,
  },
]

export const sprintIssues: Issue[] = [
  {
    id: 'issue-10',
    key: 'TT-10',
    summary: 'Auth API',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'To Do',
    assigneeId: 'user-2',
    assigneeName: 'Ivan',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'High',
    labels: ['backend', 'auth'],
    dueDate: '2026-08-15',
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: 8 * 3600,
    remainingEstimateSeconds: 8 * 3600,
    timeSpentSeconds: 0,
  },
  {
    id: 'issue-11',
    key: 'TT-11',
    summary: 'Login page',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'To Do',
    assigneeId: 'user-3',
    assigneeName: 'Anna',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'Medium',
    labels: ['frontend', 'auth'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: 6 * 3600,
    remainingEstimateSeconds: 6 * 3600,
    timeSpentSeconds: 0,
  },
  {
    id: 'issue-12',
    key: 'TT-12',
    summary: 'Password reset flow',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'To Do',
    assigneeId: 'user-2',
    assigneeName: 'Ivan',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'High',
    labels: ['backend', 'auth'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: 5 * 3600,
    remainingEstimateSeconds: 5 * 3600,
    timeSpentSeconds: 0,
  },
  {
    id: 'issue-13',
    key: 'TT-13',
    summary: 'Invite users by email',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'To Do',
    assigneeId: 'user-4',
    assigneeName: 'Petr',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'Medium',
    labels: ['backend'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: null,
    remainingEstimateSeconds: null,
    timeSpentSeconds: 0,
  },
]

export const boardIssues: Issue[] = [
  ...sprintIssues,
  {
    id: 'issue-7',
    key: 'TT-7',
    summary: 'OAuth provider integration',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'In Progress',
    assigneeId: 'user-2',
    assigneeName: 'Ivan',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'High',
    labels: ['backend', 'auth'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: 12 * 3600,
    remainingEstimateSeconds: 8 * 3600,
    timeSpentSeconds: 4 * 3600,
  },
  {
    id: 'issue-15',
    key: 'TT-15',
    summary: 'Write E2E tests',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'Done',
    assigneeId: 'user-4',
    assigneeName: 'Petr',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'Medium',
    labels: ['qa'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: 6 * 3600,
    remainingEstimateSeconds: 0,
    timeSpentSeconds: 6 * 3600,
  },
  {
    id: 'issue-16',
    key: 'TT-16',
    summary: 'Update API docs',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'Done',
    assigneeId: 'user-3',
    assigneeName: 'Anna',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'Low',
    labels: ['docs'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: null,
    remainingEstimateSeconds: null,
    timeSpentSeconds: 2 * 3600,
  },
  {
    id: 'issue-17',
    key: 'TT-17',
    summary: 'Fix navigation active state',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'Done',
    assigneeId: 'user-2',
    assigneeName: 'Ivan',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'Low',
    labels: ['ui'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: null,
    remainingEstimateSeconds: null,
    timeSpentSeconds: 3 * 3600,
  },
  {
    id: 'issue-18',
    key: 'TT-18',
    summary: 'Optimize bundle size',
    description: '',
    projectName: 'Task Tracker',
    projectKey: 'TT',
    status: 'Done',
    assigneeId: 'user-4',
    assigneeName: 'Petr',
    reporterId: 'user-1',
    reporterName: 'Anna',
    priority: 'Medium',
    labels: ['frontend', 'performance'],
    dueDate: null,
    components: [],
    versions: [],
    watchers: [],
    votes: 0,
    voted: false,
    originalEstimateSeconds: null,
    remainingEstimateSeconds: null,
    timeSpentSeconds: 4 * 3600,
  },
]

export const columns: BoardColumn[] = [
  { id: 'col-todo', name: 'To Do', wipLimit: 15, issueIds: ['issue-10', 'issue-11', 'issue-12', 'issue-13'] },
  { id: 'col-inprogress', name: 'In Progress', wipLimit: 5, issueIds: ['issue-7'] },
  { id: 'col-done', name: 'Done', wipLimit: null, issueIds: ['issue-15', 'issue-16', 'issue-17', 'issue-18'] },
]

export const activeSprint: Sprint = {
  id: 'sprint-1',
  name: 'Sprint 1',
  goal: 'Ship MVP auth and board views',
  state: 'active',
  velocity: 24,
  remainingDays: 5,
  issueIds: sprintIssues.map((i) => i.id),
}

export async function getBoard(): Promise<{ columns: BoardColumn[]; issues: Issue[]; sprint: Sprint }> {
  await new Promise((resolve) => setTimeout(resolve, 300))
  return { columns, issues: boardIssues, sprint: activeSprint }
}

export async function getBacklog(): Promise<{ sprint: Sprint; sprintIssues: Issue[]; backlogIssues: Issue[] }> {
  await new Promise((resolve) => setTimeout(resolve, 300))
  return { sprint: activeSprint, sprintIssues, backlogIssues }
}
